# Generated by Django 3.1.2 on 2021-02-19 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kp_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_division', models.CharField(max_length=200)),
                ('requester_contact', models.CharField(max_length=20)),
                ('distributer_name', models.CharField(max_length=150)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_occupation', models.CharField(choices=[('AEW', 'AEW'), ('Chef', 'Chef'), ('Dev Worker', 'Dev Worker'), ('Entrepreneur', 'Entrepreneur'), ('Farmers', 'Farmers'), ('Govt Employee', 'Govt Employee'), ('Govt Officials', 'Govt Offcials'), ('Media', 'Media'), ('OFW', 'OFW'), ('PhilRice Staff', 'PhilRice Staff'), ('Policymakers', 'Policymakers'), ('Private Company', 'Private Company'), ('Program Manager', 'Program Manager'), ('Researcher', 'Researcher'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Others', 'Others')], max_length=50, null=True)),
                ('recipient_male', models.IntegerField()),
                ('rrecipient_female', models.IntegerField()),
                ('recipient_province', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kp_request',
            },
        ),
        migrations.RenameField(
            model_name='kp_distribute',
            old_name='title',
            new_name='kp',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='date',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='distribute_name',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='reciever_female',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='reciever_male',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='reciever_name',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='reciever_occupation',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='reciever_province',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='requester_contact',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='requester_division',
        ),
        migrations.RemoveField(
            model_name='kp_distribute',
            name='requester_name',
        ),
        migrations.AddField(
            model_name='kp_distribute',
            name='request',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='devcom.kp_request'),
            preserve_default=False,
        ),
    ]
