# Generated by Django 3.1.2 on 2021-02-23 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0003_auto_20210219_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kp_request',
            old_name='rrecipient_female',
            new_name='recipient_female',
        ),
    ]
