# Generated by Django 3.1.2 on 2021-02-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0004_auto_20210223_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_distribute',
            name='date_record',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
