# Generated by Django 3.1.2 on 2021-02-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0005_kp_distribute_date_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kp_distribute',
            name='date_record',
        ),
    ]
