# Generated by Django 3.1.2 on 2021-02-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0006_remove_kp_distribute_date_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp_distribute',
            name='kp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devcom.kp_input'),
        ),
    ]
