# Generated by Django 3.1.2 on 2021-02-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0008_auto_20210224_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp_distribute',
            name='kp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devcom.kp_input'),
        ),
    ]
