# Generated by Django 3.1.2 on 2021-02-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0010_auto_20210224_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kp_distribute',
            old_name='kp',
            new_name='Kp',
        ),
        migrations.RenameField(
            model_name='kp_distribute',
            old_name='quantity',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='kp_distribute',
            old_name='request',
            new_name='Request',
        ),
    ]
