# Generated by Django 3.1.2 on 2021-03-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0012_kp_distribute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_request',
            name='datefortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
