# Generated by Django 3.1.2 on 2021-03-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0013_kp_request_datefortable'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_input',
            name='datefortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
