# Generated by Django 3.1.2 on 2021-03-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0014_kp_input_datefortable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp_distribute',
            name='Date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
