# Generated by Django 3.1.2 on 2021-03-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0015_auto_20210302_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptc',
            name='AEW',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='female',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='location1',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='location2',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='location3',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='location4',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='location5',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='male',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nlocation1',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nlocation2',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nlocation3',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nlocation4',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nlocation5',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='nsatisfied',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='ntopic1',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='ntopic2',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='ntopic3',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='other',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='response',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='satisfied',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='tfemale',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='tmale',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='topic1',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='topic3',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='year',
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH11to15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH12hto24h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH16to20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH1hto2h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH1to5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH21to25',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH24to48h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH26to30',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH2hto4h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH31to1h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH4hto8h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH6to10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NOH8hto12h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='NnotRes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH11to15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH12hto24h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH16to20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH1hto2h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH1to5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH21to25',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH24to48h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH26to30',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH2hto4h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH31to1h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH4hto8h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH6to10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH8hto12h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='PTCfemale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='PTCmale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='RCEFfemale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='RCEFmale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH11to15',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH12hto24h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH16to20',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH1hto2h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH1to5',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH21to25',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH24to48h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH26to30',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH2hto4h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH31to1h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH4hto8h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH6to10',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH8hto12h',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='WnotRes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='abra',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='agusanNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='agusanSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='aklan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='albay',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='antique',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='apayao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='aurora',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='basilan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='bataan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='batanes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='batangas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='benguet',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='biliran',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='bohol',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='bukidnon',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='bulacan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cagayan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='camarinesNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='camarinesSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='camiguin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='capiz',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='catanduanes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cavite',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cebu',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='compostela',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cotabatoNorth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cotabatoSouth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='cropEsta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='datefortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='davaoNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='davaoOriental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='davaoSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='dwntimeH',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='dwntimeM',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='foodSci',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='genInfo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='greetings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='guimaras',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='harvMng',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='ilocosNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='ilocosSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='iloilo',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='international',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='isabela',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='kalinga',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='knowProd',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='laguna',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='lanaoNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='lanaoSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='landPrep',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='launion',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='leyte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='leyteSouth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='machine',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='maguindanao',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='manila',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='masbate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='mindoroOccidental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='mindoroOriental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='misamisOccidental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='misamisOriental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='mountainProvince',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='negrosOccidental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='negrosOriental',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='notRes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='nuevaEcija',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='nuevaVizcaya',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='nutriMng',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='otherAgency',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='others',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='palawan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='palayamanan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='pampanga',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='pangasinan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='pestMng',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='philrice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='quezon',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='quirino',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rcef',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rcefComp',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rcefExt',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rcefSeed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='registration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rizal',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='romblon',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='rsbsa',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='samar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='samarEast',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='samarNorth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='sarangani',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='seedAvail',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='seedVar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='siquijor',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='sms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='smsWD',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='smsWE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='sorsogon',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='sultanKudarat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='sulu',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='surigaoNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='surigaoSur',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='tarlac',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='tawitawi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='texterNOH',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='texterOH',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='texterWD',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='texterWE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='thanks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='training',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='undetermined',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='waterMng',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='website',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='zambales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='zamboangaNorte',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ptc',
            name='zamboangaSur',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
