# Generated by Django 3.1.2 on 2021-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0018_auto_20210303_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptc',
            name='keywords',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
