# Generated by Django 3.1.2 on 2021-03-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0020_auto_20210303_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptc',
            name='NOH48hplus',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='OH48hplus',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='WOH48hplus',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
