# Generated by Django 3.1.2 on 2021-03-04 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0021_auto_20210304_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptc',
            name='zamboangaSibugay',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
