# Generated by Django 3.1.2 on 2021-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0022_ptc_zamboangasibugay'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptc',
            name='ifugao',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='marinduque',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
