# Generated by Django 3.1.2 on 2021-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0023_auto_20210304_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptc',
            name='date',
        ),
        migrations.AddField(
            model_name='ptc',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='ptc',
            name='year',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
