# Generated by Django 3.1.2 on 2021-03-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0024_auto_20210304_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptc',
            name='datefortable',
        ),
    ]
