# Generated by Django 3.1.2 on 2021-03-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0025_remove_ptc_datefortable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptc',
            name='month',
        ),
        migrations.RemoveField(
            model_name='ptc',
            name='year',
        ),
    ]
