# Generated by Django 3.1.2 on 2021-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0026_auto_20210304_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptc',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptc',
            name='datefortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
