# Generated by Django 3.1.2 on 2021-03-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0029_auto_20210309_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_page_info',
            name='month',
            field=models.IntegerField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='fb_page_info',
            name='seeds',
            field=models.IntegerField(),
        ),
    ]
