# Generated by Django 3.1.2 on 2021-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0031_fb_page_info_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_page_info',
            name='allpost',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fb_page_info',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=60, null=True),
        ),
    ]
