# Generated by Django 3.1.2 on 2021-03-11 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0035_pr_visitor_noage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr_visitor',
            old_name='redirect',
            new_name='direct',
        ),
    ]
