# Generated by Django 3.1.2 on 2021-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0036_auto_20210311_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr_visitor',
            name='sno',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pr_visitor',
            name='syes',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
