# Generated by Django 3.1.2 on 2021-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0037_auto_20210311_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pw_visitor',
            name='nsatisfied',
        ),
        migrations.RemoveField(
            model_name='pw_visitor',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='pw_visitor',
            name='satisfied',
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='desktop',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='direct',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='mobile',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='nosex',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='organic',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='pageviews',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='referral',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='sno',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='social',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='syes',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='tablet',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
