# Generated by Django 3.1.2 on 2021-03-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0038_auto_20210315_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pw_visitor',
            name='quarter',
            field=models.CharField(choices=[('1st Q', '1st Quarter'), ('2nd Q', '2nd Quarter'), ('3rd Q', '3rd Quarter'), ('4th Q', '4th Quarter')], max_length=60, null=True),
        ),
    ]
