# Generated by Django 3.1.2 on 2021-03-23 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0040_auto_20210315_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio_visitor',
            name='dateTimeAired',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
