# Generated by Django 3.1.2 on 2021-03-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0041_radio_visitor_datetimeaired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio_upload',
            name='frequency',
        ),
        migrations.AddField(
            model_name='radio_upload',
            name='respondents',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
