# Generated by Django 3.1.2 on 2021-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0042_auto_20210323_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio_visitor',
            name='month',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
