# Generated by Django 3.1.2 on 2021-03-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0043_auto_20210323_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio_visitor',
            name='day',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radio_visitor',
            name='time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radio_visitor',
            name='month',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
