# Generated by Django 3.1.2 on 2021-03-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0044_auto_20210323_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio_visitor',
            name='dateTimeAired',
        ),
    ]
