# Generated by Django 3.1.2 on 2021-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0045_remove_radio_visitor_datetimeaired'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio_visitor',
            name='title',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
