# Generated by Django 3.1.2 on 2021-03-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0046_radio_visitor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio_visitor',
            name='location',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
