# Generated by Django 3.1.2 on 2021-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0047_radio_visitor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio_visitor',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='radio_visitor',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
