# Generated by Django 3.1.2 on 2021-03-26 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0048_auto_20210324_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partners',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
