# Generated by Django 3.1.2 on 2021-03-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0049_auto_20210326_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pw',
            name='quarter',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
