# Generated by Django 3.1.2 on 2021-03-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0050_auto_20210330_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pw',
            name='quarter',
        ),
        migrations.AddField(
            model_name='pw',
            name='month',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
