# Generated by Django 3.1.2 on 2021-03-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0051_auto_20210330_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pr_upload',
            name='quarter',
        ),
        migrations.AddField(
            model_name='pr_upload',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=60, null=True),
        ),
    ]
