# Generated by Django 3.1.2 on 2021-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0052_auto_20210330_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_input',
            name='date_revised',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='kp_input_stock',
            name='printing_press',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pr_upload',
            name='topic',
            field=models.CharField(choices=[('crop', 'Crop'), ('general info', 'Genera Info'), ('harvest', 'Harvest'), ('land', 'Land'), ('machine', 'Machine'), ('nutrient', 'Nutrient'), ('palayamanan', 'Palayamanan'), ('palaycheck', 'PalayCheck'), ('pest', 'Pest'), ('planting', 'Planting'), ('postharvest', 'Postharvest'), ('rcef', 'RCEF'), ('seed', 'Seed'), ('training', 'Training'), ('water', 'Water')], max_length=60, null=True),
        ),
    ]
