# Generated by Django 3.1.2 on 2021-03-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0054_auto_20210330_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_input',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
