# Generated by Django 3.1.2 on 2021-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0055_kp_input_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='kp_survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'kp_survey',
            },
        ),
    ]
