# Generated by Django 3.1.2 on 2021-04-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0056_kp_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kp_survey',
        ),
    ]
