# Generated by Django 3.1.2 on 2021-04-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0057_delete_kp_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_input',
            name='monthfortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
