# Generated by Django 3.1.2 on 2021-04-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0059_auto_20210413_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kp_distribute',
            old_name='Date',
            new_name='Month',
        ),
        migrations.AddField(
            model_name='kp_distribute',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
