# Generated by Django 3.1.2 on 2021-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0060_auto_20210413_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_request',
            name='monthfortable',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
