# Generated by Django 3.1.2 on 2021-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0061_kp_request_monthfortable'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
