# Generated by Django 3.1.2 on 2021-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0062_auto_20210427_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='awards',
            name='awardee',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='sponsor',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=60, null=True),
        ),
    ]
