# Generated by Django 3.1.2 on 2021-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0063_auto_20210427_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='adress',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='contact',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='edate',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ongoing', 'Ongoing'), ('EOC', 'End of Contract')], max_length=20, null=True),
        ),
    ]
