# Generated by Django 3.1.2 on 2021-04-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0064_auto_20210428_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='media/'),
            preserve_default=False,
        ),
    ]
