# Generated by Django 3.1.2 on 2021-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0065_staff_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progproj',
            name='project',
        ),
        migrations.AddField(
            model_name='progproj',
            name='ar',
            field=models.FileField( upload_to='ar/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progproj',
            name='budget',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progproj',
            name='cowork',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progproj',
            name='leader',
            field=models.CharField( max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progproj',
            name='protocol',
            field=models.FileField( upload_to='protocol/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progproj',
            name='staff',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progproj',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('terminated', 'Terminated'), ('onhold', 'Onhold')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(upload_to='staff/'),
        ),
    ]
