# Generated by Django 3.1.2 on 2021-05-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0066_auto_20210428_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pw_visitor',
            name='quarter',
        ),
        migrations.AddField(
            model_name='pw_visitor',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=60, null=True),
        ),
    ]
