# Generated by Django 3.1.2 on 2021-05-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0070_auto_20210511_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kp_input_stock',
            name='date_recorded',
            field=models.DateTimeField(),
        ),
    ]
