# Generated by Django 3.1.2 on 2021-05-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devcom', '0071_auto_20210511_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='kp_distribute',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
